//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARCustomer()
        {
            this.ARCustomers1 = new HashSet<ARCustomer>();
            this.ARCustomers11 = new HashSet<ARCustomer>();
            this.SCContracts = new HashSet<SCContract>();
            this.SCContracts1 = new HashSet<SCContract>();
            this.SCContracts2 = new HashSet<SCContract>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<int> BillToID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string Attn { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public bool Prospect { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> ShipMethodID { get; set; }
        public string EIN { get; set; }
        public Nullable<int> SalesRepID { get; set; }
        public decimal CreditLimit { get; set; }
        public int PriceLevelID { get; set; }
        public bool DoFinCharges { get; set; }
        public Nullable<int> AdjustmentID { get; set; }
        public Nullable<int> TaxCodeID { get; set; }
        public bool Taxable { get; set; }
        public string TaxNumber { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string BlanketPO { get; set; }
        public bool Hold { get; set; }
        public string Remarks { get; set; }
        public decimal Invoices { get; set; }
        public decimal Unapplied { get; set; }
        public decimal Orders { get; set; }
        public bool Active { get; set; }
        public bool ShipTo { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public bool CompanyCustomer { get; set; }
        public Nullable<int> CustomPriceLevelID { get; set; }
        public bool EnableCustomPricing { get; set; }
        public Nullable<int> ChargeMethodID { get; set; }
        public Nullable<int> EquipmentContactID { get; set; }
        public Nullable<int> DecisionContactID { get; set; }
        public Nullable<int> ARContactID { get; set; }
        public bool AllowAutoMeterRequests { get; set; }
        public int Locks { get; set; }
        public int DBFileHeaderID { get; set; }
        public bool HideBillToOrdersEinfo { get; set; }
        public Nullable<int> OnHoldCodeID { get; set; }
        public Nullable<int> TimeZoneCodeID { get; set; }
        public Nullable<int> OnSiteWarehouseID { get; set; }
        public string CreatorID { get; set; }
        public string UpdatorID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public byte[] timestamp { get; set; }
        public bool AllowAutoOnHoldUpdates { get; set; }
        public Nullable<int> MailToID { get; set; }
        public Nullable<int> ShTrackingConfigID { get; set; }
        public bool RequirePONum { get; set; }
        public bool ConsolidatedBillingEnabled { get; set; }
        public decimal ConsolidatedBillingMinBillingAmount { get; set; }
        public int ConsolidatedBillingFlag { get; set; }
        public int ConsolidatedBillingDefaultMin { get; set; }
        public Nullable<int> ConsolidatedBillingCycleID { get; set; }
        public Nullable<System.DateTime> ConsolidatedBillingNextBillingDate { get; set; }
        public bool InheritParentCustomPrices { get; set; }
        public bool SendStatements { get; set; }
        public bool UseBillToAddress { get; set; }
        public string BillToAttn { get; set; }
        public string BillToAddress { get; set; }
        public string BillToCity { get; set; }
        public string BillToCounty { get; set; }
        public string BillToState { get; set; }
        public string BillToZip { get; set; }
        public string BillToCountry { get; set; }
        public bool UseMapAddress { get; set; }
        public string MapAddress { get; set; }
        public string MapCity { get; set; }
        public string MapState { get; set; }
        public string MapZip { get; set; }
        public string MapCountry { get; set; }
        public decimal Miles { get; set; }
        public Nullable<int> NoteID { get; set; }
        public int NoteFlag { get; set; }
        public bool WarnOnPODuplicate { get; set; }
        public Nullable<int> MeterContactID { get; set; }
        public bool ShowInAllBranches { get; set; }
        public byte InvoiceMethod { get; set; }
        public Nullable<int> ARRepID { get; set; }
        public int NoteCount { get; set; }
        public Nullable<int> EquipmentShipToContactID { get; set; }
        public Nullable<int> TaxExemptCodeID { get; set; }
        public Nullable<int> SLACodeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCustomer> ARCustomers1 { get; set; }
        public virtual ARCustomer ARCustomer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCustomer> ARCustomers11 { get; set; }
        public virtual ARCustomer ARCustomer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts2 { get; set; }
    }
}
