//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetReplacement
    {
        public int ReplacementID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ReplacementDate { get; set; }
        public string OldSerialNumber { get; set; }
        public string OldModel { get; set; }
        public string NewSerialNumber { get; set; }
        public string NewModel { get; set; }
        public Nullable<decimal> ReplacementValue { get; set; }
        public string Comments { get; set; }
        public string ScheduleNumber { get; set; }
    }
}
