//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseHistory
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public Nullable<System.DateTime> OverrideDate { get; set; }
        public Nullable<decimal> PreBase { get; set; }
        public Nullable<decimal> FprBase { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
