//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientData
    {
        public long RevisionID { get; set; }
        public string ERPCustomerNumber { get; set; }
        public int ERPContractID { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public double BaseContractAmount { get; set; }
        public double AffectedCost { get; set; }
        public double PayOffAmount { get; set; }
        public int BilledID { get; set; }
        public Nullable<int> useOverrideVolume { get; set; }
        public Nullable<System.DateTime> OverrideDate { get; set; }
        public Nullable<decimal> OverrideExpense { get; set; }
        public Nullable<int> useOverrideVolumeFPR { get; set; }
        public Nullable<System.DateTime> OverrideDateFPR { get; set; }
        public Nullable<decimal> OverrideExpenseFPR { get; set; }
        public Nullable<int> Modified { get; set; }
        public Nullable<System.DateTime> OverrideContractStartDate { get; set; }
    }
}
