//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSetting
    {
        public int SettingsID { get; set; }
        public int ClientID { get; set; }
        public string SettingsValue { get; set; }
        public string SettingsType { get; set; }
    }
}
