//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostAllocationMeterGroup
    {
        public int SettingsMeterGroupID { get; set; }
        public int CustomerID { get; set; }
        public long MeterGroupID { get; set; }
        public decimal ExcessCPP { get; set; }
        public Nullable<int> ContractMeterGroupID { get; set; }
        public string ContractMeterGroup { get; set; }
    }
}
