//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleReconciliationService
    {
        public long CycleReconciliationServiceId { get; set; }
        public long CycleId { get; set; }
        public string MeterGroup { get; set; }
        public decimal Credit { get; set; }
    
        public virtual Cycle Cycle { get; set; }
    }
}
