//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyclePeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CyclePeriod()
        {
            this.CyclePeriodSchedules = new HashSet<CyclePeriodSchedule>();
        }
    
        public long CyclePeriodId { get; set; }
        public long CycleId { get; set; }
        public System.DateTime Period { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual Cycle Cycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyclePeriodSchedule> CyclePeriodSchedules { get; set; }
    }
}
