//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CyclePeriodSchedule
    {
        public long CyclePeriodScheduleId { get; set; }
        public long CyclePeriodId { get; set; }
        public long ScheduleId { get; set; }
        public decimal InstancesInvoiced { get; set; }
    
        public virtual CyclePeriod CyclePeriod { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
