//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cycle()
        {
            this.CyclePeriods = new HashSet<CyclePeriod>();
            this.CycleReconciliationServices = new HashSet<CycleReconciliationService>();
        }
    
        public long CycleId { get; set; }
        public long CustomerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool InActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDateTime { get; set; }
        public bool InvisibleToClient { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsReconciled { get; set; }
        public decimal ReconcileAdj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CyclePeriod> CyclePeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CycleReconciliationService> CycleReconciliationServices { get; set; }
    }
}
