//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public long DeviceId { get; set; }
        public Nullable<long> ScheduleId { get; set; }
        public long CustomerId { get; set; }
        public string EquipmentId { get; set; }
        public string EquipmentNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDateTime { get; set; }
        public string RemovedStatus { get; set; }
        public decimal MonthlyCost { get; set; }
        public Nullable<System.DateTimeOffset> RemovalDateTime { get; set; }
        public string Disposition { get; set; }
    }
}
