//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class easylinkimport
    {
        public int EasylinkImportID { get; set; }
        public Nullable<int> ImportID { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<int> Child { get; set; }
        public string emailaddress { get; set; }
        public string FaxNumber { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public string Messages { get; set; }
    }
}
