//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyLinkPagesByClient
    {
        public int MappingID { get; set; }
        public string emailaddress { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public string FaxNumber { get; set; }
    }
}
