//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentManager
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> IntroDate { get; set; }
        public Nullable<int> MFRMoVol { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
