//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlobalViewEntities : DbContext
    {
        public GlobalViewEntities()
            : base("name=GlobalViewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetReplacement> AssetReplacements { get; set; }
        public virtual DbSet<ContactClient> ContactClients { get; set; }
        public virtual DbSet<FprContact> FprContacts { get; set; }
        public virtual DbSet<EquipmentManager> EquipmentManagers { get; set; }
        public virtual DbSet<EquipmentManagerList> EquipmentManagerLists { get; set; }
        public virtual DbSet<GlobalViewUser> GlobalViewUsers { get; set; }
        public virtual DbSet<ClientContact> ClientContacts { get; set; }
    }
}
