//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrisCall
    {
        public int ID { get; set; }
        public string CallNumber { get; set; }
        public Nullable<System.DateTime> CallDateTime { get; set; }
        public string FPRID { get; set; }
    }
}
