//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long LocationId { get; set; }
        public long CustomerId { get; set; }
        public string Name { get; set; }
        public decimal TaxRate { get; set; }
        public bool IsCorporate { get; set; }
        public System.DateTimeOffset CreatedDateTime { get; set; }
        public Nullable<System.DateTimeOffset> ModifiedDateTime { get; set; }
        public bool IsDeleted { get; set; }
        public int CoFreedomLocationId { get; set; }
    }
}
