//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LockInvoice
    {
        public int ID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> ErpContractID { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
