//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterGroupsDataView
    {
        public long MeterGroupID { get; set; }
        public Nullable<int> ERPMeterGroupID { get; set; }
        public string MeterGroupDesc { get; set; }
        public Nullable<double> AuditExpense { get; set; }
        public Nullable<decimal> AuditVolume { get; set; }
        public decimal CPP { get; set; }
        public Nullable<int> ERPContractID { get; set; }
        public string ERPMeterGroupDesc { get; set; }
        public string ID { get; set; }
        public Nullable<int> invoiceID { get; set; }
        public Nullable<int> UniqueID { get; set; }
    }
}
