//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodNote
    {
        public int NoteID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public string PeriodNote1 { get; set; }
    }
}
