//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterlyRollover
    {
        public int ContractID { get; set; }
        public Nullable<System.DateTime> OverageFromDate { get; set; }
        public Nullable<System.DateTime> OverageToDate { get; set; }
        public int InvoiceID { get; set; }
        public int ContractMeterGroupID { get; set; }
        public string ERPMeterGroupDesc { get; set; }
        public Nullable<decimal> Rollovers { get; set; }
        public decimal CPP { get; set; }
    }
}
