//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RevisionDataEntities : DbContext
    {
        public RevisionDataEntities()
            : base("name=RevisionDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaseHistory> BaseHistories { get; set; }
        public virtual DbSet<BillingTypeReference> BillingTypeReferences { get; set; }
        public virtual DbSet<ClientData> ClientDatas { get; set; }
        public virtual DbSet<IntegrisCall> IntegrisCalls { get; set; }
        public virtual DbSet<LockInvoice> LockInvoices { get; set; }
        public virtual DbSet<MeterGroup> MeterGroups { get; set; }
        public virtual DbSet<PeriodNote> PeriodNotes { get; set; }
        public virtual DbSet<RevisionData> RevisionDatas { get; set; }
        public virtual DbSet<VisionData> VisionDatas { get; set; }
        public virtual DbSet<VisionHistory> VisionHistories { get; set; }
        public virtual DbSet<MeterGroupsDataView> MeterGroupsDataViews { get; set; }
        public virtual DbSet<PeriodHistoryWithNote> PeriodHistoryWithNotes { get; set; }
        public virtual DbSet<PeriodNotesView> PeriodNotesViews { get; set; }
        public virtual DbSet<RevisionDataView> RevisionDataViews { get; set; }
        public virtual DbSet<RolloverView> RolloverViews { get; set; }
    }
}
