//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionData
    {
        public int RevisionID { get; set; }
        public int InvoiceID { get; set; }
        public int ContractID { get; set; }
        public int MeterGroupID { get; set; }
        public Nullable<int> Rollover { get; set; }
        public Nullable<decimal> Credits { get; set; }
    }
}
