//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionData
    {
        public long RevisionDataID { get; set; }
        public Nullable<int> ERPContractID { get; set; }
        public Nullable<int> ERPMeterGroupID { get; set; }
        public string ERPMeterGroupDesc { get; set; }
        public Nullable<long> ContractedVolume { get; set; }
        public Nullable<long> ActualVolume { get; set; }
        public Nullable<decimal> CPPRate { get; set; }
        public Nullable<long> VolumeOffset { get; set; }
        public Nullable<System.DateTime> PeriodDate { get; set; }
        public Nullable<int> Rollover { get; set; }
        public Nullable<decimal> Credits { get; set; }
        public Nullable<decimal> FBRContractBase { get; set; }
        public Nullable<decimal> ClientContractBase { get; set; }
        public Nullable<decimal> ClientCPP { get; set; }
        public int datachecksum { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
