//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionDataView
    {
        public int InvoiceID { get; set; }
        public Nullable<decimal> ContractVolume { get; set; }
        public Nullable<decimal> ActualVolume { get; set; }
        public Nullable<decimal> Overage { get; set; }
        public Nullable<int> Rollover { get; set; }
        public Nullable<decimal> CPP { get; set; }
        public int CreditAmount { get; set; }
        public Nullable<System.DateTime> OverageToDate { get; set; }
        public int ContractMeterGroupID { get; set; }
        public int ContractID { get; set; }
        public Nullable<System.DateTime> OverageFromDate { get; set; }
        public string MeterGroup { get; set; }
        public Nullable<decimal> OverageCharge { get; set; }
        public Nullable<int> RevisionID { get; set; }
    }
}
