//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCBillingCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCBillingCycle()
        {
            this.SCContracts = new HashSet<SCContract>();
            this.SCContracts1 = new HashSet<SCContract>();
            this.SCContracts2 = new HashSet<SCContract>();
            this.SCContracts3 = new HashSet<SCContract>();
            this.SCContractMeterGroups = new HashSet<SCContractMeterGroup>();
        }
    
        public int BillingCycleID { get; set; }
        public string BillingCycle { get; set; }
        public string Description { get; set; }
        public short Days { get; set; }
        public short Months { get; set; }
        public short Years { get; set; }
        public bool Active { get; set; }
        public int Locks { get; set; }
        public string CreatorID { get; set; }
        public string UpdatorID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public byte[] timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContract> SCContracts3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCContractMeterGroup> SCContractMeterGroups { get; set; }
    }
}
