//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCEquipmentCustomProperty
    {
        public int EquipmentCustomPropertyID { get; set; }
        public int EquipmentID { get; set; }
        public int ShAttributeID { get; set; }
        public Nullable<int> IDVal { get; set; }
        public string TextVal { get; set; }
        public bool Required { get; set; }
        public string CreatorID { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
