//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleCostCenter
    {
        public int ScheduleCostCenterID { get; set; }
        public long ScheduleID { get; set; }
        public long CustomerID { get; set; }
        public string CostCenter { get; set; }
        public Nullable<long> MeterGroupID { get; set; }
        public Nullable<int> Volume { get; set; }
    }
}
