//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int SurveyQuestionsID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Question { get; set; }
        public Nullable<decimal> AnswerNumeric { get; set; }
        public string AnswerText { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> NA { get; set; }
    }
}
