//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SCEquipmentPreview_Custom
    {
        public int EquipmentID { get; set; }
        public string EquipmentNumber { get; set; }
        public Nullable<int> SerialNumberID { get; set; }
        public int CustomerID { get; set; }
        public string EquipStatus { get; set; }
        public string EquipCondition { get; set; }
        public Nullable<decimal> LastMeter { get; set; }
        public string CustomerName { get; set; }
        public string LocationName { get; set; }
        public bool Hosting { get; set; }
        public bool Attached { get; set; }
    }
}
