//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisionData
    {
        public int RevisionDataID { get; set; }
        public Nullable<int> ERPContractID { get; set; }
        public string clientPeriodDates { get; set; }
        public Nullable<double> clientOverageCost { get; set; }
        public Nullable<double> fprOverageCost { get; set; }
        public Nullable<double> fprCost { get; set; }
        public Nullable<double> credits { get; set; }
        public Nullable<double> savings { get; set; }
        public Nullable<double> pct { get; set; }
        public Nullable<double> clientCost { get; set; }
        public Nullable<double> FPRBase { get; set; }
        public Nullable<double> ClientBase { get; set; }
    }
}
