//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_admin_EquipmentList_MeterGroup
    {
        public int EquipmentID { get; set; }
        public string CustomerName { get; set; }
        public string EquipmentNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public string ModelCategory { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> MostRecentDefaultMeterReadingDate { get; set; }
        public Nullable<decimal> MostRecentDefaultMeterReadingDisplay { get; set; }
        public Nullable<decimal> AvgMonthlyVolume { get; set; }
        public string LocName { get; set; }
        public string Building { get; set; }
        public string AssetUser { get; set; }
        public string Floor { get; set; }
        public string Department { get; set; }
        public string CostCenter { get; set; }
        public string Address { get; set; }
        public string OwnershipType { get; set; }
        public string ScheduleNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Technician { get; set; }
        public string OnSiteWarehouse { get; set; }
        public string SupplyProviderPrefFullName { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> NumberOfContractsActive { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> SupplyProvider { get; set; }
        public string Location { get; set; }
        public string DeviceReplacementExpires { get; set; }
        public Nullable<bool> Service_Replacement { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> BillToID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
    }
}
