//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BillingMeterVolumesByDevice
    {
        public int InvoiceID { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
        public Nullable<decimal> BWDisplay { get; set; }
        public Nullable<decimal> BWVolume { get; set; }
        public int EquipmentID { get; set; }
        public string EquipmentNumber { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<decimal> ColorDisplay { get; set; }
        public Nullable<decimal> ColorVolume { get; set; }
    }
}
