//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CSQuarterlyHistoryByInvoice
    {
        public string InvoiceNumber { get; set; }
        public string ContractMeterGroup { get; set; }
        public Nullable<decimal> CountedCopies { get; set; }
        public Nullable<decimal> CoveredCopies { get; set; }
        public Nullable<decimal> BillableCopies { get; set; }
        public Nullable<decimal> TotalChargeAmount { get; set; }
        public Nullable<decimal> EffectiveRate { get; set; }
        public Nullable<decimal> RolloverUsage { get; set; }
        public Nullable<decimal> RolloverUsageChange { get; set; }
        public int CustomerID { get; set; }
    }
}
