//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_csSCBillingContracts
    {
        public int ContractID { get; set; }
        public string OverageFromDate { get; set; }
        public string OverageToDate { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public int VoidFlag { get; set; }
    }
}
