//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PagesOnContract
    {
        public string Description { get; set; }
        public string GROUP { get; set; }
        public Nullable<decimal> Pages { get; set; }
        public short Months { get; set; }
        public string BillingCycle { get; set; }
        public int BillingCycleID { get; set; }
        public Nullable<decimal> MonthlyPages { get; set; }
    }
}
