//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QuarterlyModelMatrix
    {
        public int InvoiceID { get; set; }
        public string Model { get; set; }
        public Nullable<int> ModelCount { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string ModelCategory { get; set; }
    }
}
