//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServiceCallandContact
    {
        public int CallID { get; set; }
        public string CallNumber { get; set; }
        public string CustomerNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> EmailType { get; set; }
        public string Email { get; set; }
        public string Primary_Email { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    }
}
