//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SurveySummaryList
    {
        public int SurveyID { get; set; }
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> SurveyDate { get; set; }
        public Nullable<decimal> Answer1 { get; set; }
        public string Comment1 { get; set; }
        public Nullable<decimal> Answer2 { get; set; }
        public string Comment2 { get; set; }
        public Nullable<decimal> Answer3 { get; set; }
        public string Comment3 { get; set; }
        public Nullable<decimal> Answer4 { get; set; }
        public string Comment4 { get; set; }
        public Nullable<decimal> Answer5 { get; set; }
        public string Comment5 { get; set; }
        public string SurveyComments { get; set; }
        public string CustomerName { get; set; }
    }
}
