//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GVWebapi.RemoteData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WeeklyServiceCalls
    {
        public int Row { get; set; }
        public string Day { get; set; }
        public Nullable<int> ThisWeek { get; set; }
        public Nullable<int> LastWeek { get; set; }
    }
}
